import os
import io
import base64
import logging
import numpy as np
import soundfile as sf
from kokoro import KPipeline
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("swarm_backend.voice")

class KokoroVoiceService:
    def __init__(self):
        self.pipeline_en = None
        self.pipeline_hi = None
        
        # Make voices configurable via environment variables
        self.voice_en = os.environ.get("KOKORO_VOICE_EN", "af_bella")
        self.voice_hi = os.environ.get("KOKORO_VOICE_HI", "hf_beta")

    def _get_pipeline(self, lang_code: str) -> KPipeline:
        if lang_code == "h":
            if self.pipeline_hi is None:
                logger.info("Initializing Kokoro Hindi pipeline...")
                self.pipeline_hi = KPipeline(lang_code="h")
            return self.pipeline_hi
        else:
            if self.pipeline_en is None:
                logger.info("Initializing Kokoro English pipeline...")
                self.pipeline_en = KPipeline(lang_code="a")
            return self.pipeline_en

    def generate_audio_base64(self, text: str, language: str) -> str:
        """
        Generates audio for the given text using Kokoro and returns a base64 string.
        Returns None if generation fails.
        """
        if not text or not text.strip():
            return None

        try:
            # Determine language code and voice
            lang = language.lower()
            if lang in ["hindi"]:
                pipeline = self._get_pipeline("h")
                voice = self.voice_hi
            else:
                # Default to English pipeline for English and Hinglish
                pipeline = self._get_pipeline("a")
                voice = self.voice_en
            
            logger.info(f"Generating audio using Kokoro voice: {voice}")
            
            generator = pipeline(text, voice=voice, speed=1.0)
            audio_chunks = []
            
            for _, _, audio in generator:
                audio_chunks.append(audio)
                
            if not audio_chunks:
                logger.warning("No audio chunks generated by Kokoro.")
                return None
                
            final_audio = np.concatenate(audio_chunks)
            
            # Save to in-memory buffer
            buffer = io.BytesIO()
            sf.write(buffer, final_audio, 24000, format='WAV')
            buffer.seek(0)
            
            # Encode to base64
            audio_base64 = base64.b64encode(buffer.read()).decode('utf-8')
            return f"data:audio/wav;base64,{audio_base64}"
            
        except Exception as e:
            logger.error(f"Error generating voice audio: {e}")
            return None

# Singleton instance
voice_service = KokoroVoiceService()
