import { motion } from 'framer-motion'
import { CalendarCheck, Check, Volume2, Play, Square, VolumeX } from 'lucide-react'
import { DAY_PLAN_TASKS, VOICE_NARRATION } from '../data/agents'

const listContainerVariants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.2
    }
  }
}

const taskItemVariants = {
  hidden: { opacity: 0, x: -20 },
  show: {
    opacity: 1,
    x: 0,
    transition: { duration: 0.4, ease: [0.16, 1, 0.3, 1] }
  }
}

export default function DayPlanOutput({ tasks = DAY_PLAN_TASKS, voiceNarration = VOICE_NARRATION, speechActive, onPlay, onStop }) {
  return (
    <div className="day-plan-card glass-panel pulse-glow">
      <div className="day-plan-header">
        <CalendarCheck size={24} className="day-plan-header-icon" />
        <div className="day-plan-title">
          <h3>Priya&apos;s Perfect Day Plan</h3>
          <p>Generated by your 5-agent swarm · All tasks sequenced and ready</p>
        </div>
      </div>

      <motion.div
        className="tasks-timeline"
        variants={listContainerVariants}
        initial="hidden"
        animate="show"
      >
        {tasks.map((task) => (
          <motion.div
            key={task.time}
            className="task-item"
            variants={taskItemVariants}
          >
            <div className="task-time-pill">{task.time}</div>
            <div className="task-detail">
              <strong>{task.title}</strong>
              <span>{task.description}</span>
            </div>
            <div className="task-status-badge">
              <Check size={12} />
              <span>{task.status}</span>
            </div>
          </motion.div>
        ))}
      </motion.div>

      {/* Big Speak Plan Button */}
      <div className="flex flex-col gap-3 mt-6">
        <button
          type="button"
          className={`speak-plan-btn ${speechActive ? 'active' : ''}`}
          onClick={speechActive ? onStop : onPlay}
        >
          <Volume2 size={16} color="rgba(255, 255, 255, 0.85)" />
          <span>{speechActive ? 'Stop Speaking' : 'Speak Plan'}</span>
          {speechActive && <span className="speak-status-dot" />}
        </button>

        <button
          type="button"
          className="speak-plan-btn secondary-voice-btn"
          onClick={() => {
            alert("🎙️ Sarvam Voice API activation coming soon!")
          }}
        >
          <Volume2 size={16} color="rgba(255, 255, 255, 0.75)" />
          <span>Speak with Sarvam Voice</span>
        </button>

        <div className="voice-preview-box">
          <p className="voice-text">
            &ldquo;{voiceNarration}&rdquo;
          </p>
        </div>
      </div>
    </div>
  )
}
