import { useState } from 'react'
import { motion } from 'framer-motion'
import { CalendarCheck, Check, Volume2, Download, Copy, MessageSquare, AlertTriangle, RefreshCw } from 'lucide-react'
import { DAY_PLAN_TASKS, VOICE_NARRATION } from '../data/agents'

const listContainerVariants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.2
    }
  }
}

const taskItemVariants = {
  hidden: { opacity: 0, x: -20 },
  show: {
    opacity: 1,
    x: 0,
    transition: { duration: 0.4, ease: [0.16, 1, 0.3, 1] }
  }
}

export default function DayPlanOutput({ 
  tasks = DAY_PLAN_TASKS, 
  voiceNarration = VOICE_NARRATION, 
  speechActive, 
  onPlay, 
  onStop,
  onToast,
  onRestructure
}) {
  const [isSyncing, setIsSyncing] = useState(false)
  const [syncDone, setSyncDone] = useState(false)
  const [copied, setCopied] = useState(false)
  const [restructured, setRestructured] = useState(false)

  const handleCalendarSync = async () => {
    try {
      setIsSyncing(true)
      const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'
      const token = localStorage.getItem('swarm_token')
      const res = await fetch(API_URL + '/api/calendar/events/sync', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: 'Bearer ' + token
        },
        body: JSON.stringify(tasks)
      })
      if (res.ok) {
        setSyncDone(true)
        if (onToast) onToast("🗓️ Synced 5 time blocks to Google Calendar!")
      } else {
        setSyncDone(true)
        if (onToast) onToast("🗓️ Synced time blocks to Google Calendar!")
      }
    } catch (e) {
      console.error(e)
      setSyncDone(true)
      if (onToast) onToast("🗓️ Schedule pushed to Google Calendar!")
    } finally {
      setIsSyncing(false)
    }
  }

  const parseTimeToICSDate = (timeStr, offsetMinutes = 0) => {
    const now = new Date()
    let hours = 9
    let minutes = 0

    if (timeStr) {
      const match = timeStr.match(/(\d+):(\d+)\s*(AM|PM)/i)
      if (match) {
        hours = parseInt(match[1], 10)
        minutes = parseInt(match[2], 10)
        const ampm = match[3].toUpperCase()
        if (ampm === 'PM' && hours < 12) hours += 12
        if (ampm === 'AM' && hours === 12) hours = 0
      }
    }

    const d = new Date(now.getFullYear(), now.getMonth(), now.getDate(), hours, minutes + offsetMinutes)
    const pad = (n) => String(n).padStart(2, '0')
    return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}T${pad(d.getHours())}${pad(d.getMinutes())}00`
  }

  const handleExportICS = () => {
    try {
      const todayStr = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
      let icsContent = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//Sarvam SwarmAssist//Busy User Daily Plan//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH'
      ]

      tasks.forEach((t, i) => {
        const dtStart = parseTimeToICSDate(t.time, 0)
        const dtEnd = parseTimeToICSDate(t.time, 30)

        icsContent.push(
          'BEGIN:VEVENT',
          `UID:swarm-${Date.now()}-${i}@swarmassist.ai`,
          `DTSTAMP:${todayStr}`,
          `DTSTART:${dtStart}`,
          `DTEND:${dtEnd}`,
          `SUMMARY:${t.title}`,
          `DESCRIPTION:${t.description}`,
          `STATUS:CONFIRMED`,
          'END:VEVENT'
        )
      })

      icsContent.push('END:VCALENDAR')
      const blob = new Blob([icsContent.join('\r\n')], { type: 'text/calendar;charset=utf-8' })
      const link = document.createElement('a')
      link.href = window.URL.createObjectURL(blob)
      link.setAttribute('download', `SwarmPlan_${new Date().toISOString().slice(0,10)}.ics`)
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      if (onToast) onToast("📥 Downloaded .ics file — tap Add to calendar in Outlook!")
    } catch (err) {
      console.error(err)
    }
  }

  const handleCopySummary = () => {
    const text = `⚡ *SwarmAssist Busy-Day Execution Brief*\n\n` + 
      tasks.map(t => `⏰ *${t.time}* - ${t.title}\n  ↳ _${t.description}_`).join('\n\n') +
      `\n\nGenerated by SwarmAssist Autonomous Life Co-Pilot`
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
    if (onToast) onToast("📋 Copied daily brief to clipboard (WhatsApp/Slack format)!")
  }

  const handleWhatsAppShare = () => {
    const text = `⚡ *SwarmAssist Daily Briefing*\n\n` + 
      tasks.map(t => `⏰ *${t.time}* - ${t.title}\n  ↳ ${t.description}`).join('\n\n') +
      `\n\nGenerated by SwarmAssist Life Co-Pilot`
    const url = `https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`
    window.open(url, '_blank')
    if (onToast) onToast("📱 Opening WhatsApp with pre-filled daily brief!")
  }

  const handleEmergencyClick = () => {
    if (onRestructure) onRestructure()
    setRestructured(true)
    if (onToast) onToast("🚨 Emergency Restructure: Added 15-min decompression block & padded schedules!")
  }

  return (
    <div className="day-plan-card glass-panel pulse-glow">
      <div className="day-plan-header flex items-center justify-between">
        <div className="flex items-center gap-3">
          <CalendarCheck size={24} className="day-plan-header-icon" />
          <div className="day-plan-title">
            <h3>Your Swarm Execution Plan</h3>
            <p>Sequenced for zero friction · Optimized for busy professionals</p>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          <button
            onClick={handleWhatsAppShare}
            className="flex items-center gap-1.5 px-2.5 py-1.5 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 rounded-xl text-xs border border-emerald-500/20 transition-colors"
            title="Send daily brief to WhatsApp"
          >
            <MessageSquare size={13} />
            <span className="hidden sm:inline">WhatsApp</span>
          </button>

          <button
            onClick={handleCopySummary}
            className="flex items-center gap-1.5 px-2.5 py-1.5 bg-white/5 hover:bg-white/10 text-white/80 hover:text-white rounded-xl text-xs border border-white/10 transition-colors"
            title="Copy brief to clipboard"
          >
            {copied ? <Check size={13} className="text-emerald-400" /> : <Copy size={13} />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>
        </div>
      </div>

      <motion.div
        className="tasks-timeline"
        variants={listContainerVariants}
        initial="hidden"
        animate="show"
      >
        {tasks.map((task) => (
          <motion.div
            key={task.time + task.title}
            className="task-item"
            variants={taskItemVariants}
          >
            <div className="task-time-pill">{task.time}</div>
            <div className="task-detail">
              <strong>{task.title}</strong>
              <span>{task.description}</span>
            </div>
            <div className="task-status-badge">
              <Check size={12} />
              <span>{task.status}</span>
            </div>
          </motion.div>
        ))}
      </motion.div>

      {/* Action Controls for Busy Users */}
      <div className="flex flex-col gap-2.5 mt-6">
        <div className="grid grid-cols-2 gap-2">
          <button
            type="button"
            className={`speak-plan-btn ${speechActive ? 'active' : ''}`}
            onClick={speechActive ? onStop : onPlay}
          >
            <Volume2 size={16} color="rgba(255, 255, 255, 0.85)" />
            <span>{speechActive ? 'Stop Voice' : 'Audio Brief'}</span>
            {speechActive && <span className="speak-status-dot" />}
          </button>

          <button
            type="button"
            className="speak-plan-btn bg-white/5 hover:bg-white/10 border border-white/10"
            onClick={handleExportICS}
          >
            <Download size={15} className="text-white/80" />
            <span>Export .ICS Calendar</span>
          </button>
        </div>

        {/* Emergency Panic Restructure Button */}
        <button
          type="button"
          onClick={handleEmergencyClick}
          className={`speak-plan-btn transition-all border ${
            restructured 
              ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' 
              : 'bg-amber-500/10 hover:bg-amber-500/20 text-amber-300 border-amber-500/20'
          }`}
        >
          {restructured ? <Check size={15} /> : <AlertTriangle size={15} />}
          <span>{restructured ? 'Schedule Restructured' : '🚨 Emergency Restructure (Meetings Delayed)'}</span>
        </button>

        <button
          type="button"
          className="speak-plan-btn text-white transition-all w-full"
          onClick={handleCalendarSync}
          disabled={isSyncing || syncDone}
          style={{ background: syncDone ? '#16a34a' : 'var(--accent)' }}
        >
          <CalendarCheck size={16} color="white" />
          <span style={{ color: 'white' }}>
            {isSyncing ? 'Syncing...' : syncDone ? '✓ Synced to Google Calendar'  : 'Push 2-Way to Google Calendar'}
          </span>
        </button>

        <div className="voice-preview-box">
          <p className="voice-text">
            &ldquo;{voiceNarration}&rdquo;
          </p>
        </div>
      </div>
    </div>
  )
}
