import { motion } from 'framer-motion'
import { CalendarCheck, Check, Volume2, Play, Square, VolumeX } from 'lucide-react'
import { DAY_PLAN_TASKS, VOICE_NARRATION } from '../data/agents'

const listContainerVariants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.2
    }
  }
}

const taskItemVariants = {
  hidden: { opacity: 0, x: -20 },
  show: {
    opacity: 1,
    x: 0,
    transition: { duration: 0.4, ease: [0.16, 1, 0.3, 1] }
  }
}

export default function DayPlanOutput({ speechActive, onPlay, onStop }) {
  return (
    <div className="day-plan-card glass-panel pulse-glow">
      <div className="day-plan-header">
        <CalendarCheck size={24} className="day-plan-header-icon" />
        <div className="day-plan-title">
          <h3>Priya&apos;s Perfect Day Plan</h3>
          <p>Generated by your 5-agent swarm · All tasks sequenced and ready</p>
        </div>
      </div>

      <motion.div
        className="tasks-timeline"
        variants={listContainerVariants}
        initial="hidden"
        animate="show"
      >
        {DAY_PLAN_TASKS.map((task) => (
          <motion.div
            key={task.time}
            className="task-item"
            variants={taskItemVariants}
          >
            <div className="task-time-pill">{task.time}</div>
            <div className="task-detail">
              <strong>{task.title}</strong>
              <span>{task.description}</span>
            </div>
            <div className="task-status-badge">
              <Check size={12} />
              <span>{task.status}</span>
            </div>
          </motion.div>
        ))}
      </motion.div>

      {/* Voice preview narrating section */}
      <div className="voice-preview-box">
        <div className="voice-box-header">
          <div className="voice-title">
            <Volume2 size={16} className="text-indigo-400" />
            <span>Voice Narrator — Sarvam Samvaad (audio preview)</span>
          </div>

          <div className="audio-controls">
            {speechActive ? (
              <button
                type="button"
                className="audio-btn active"
                onClick={onStop}
                title="Stop Audio"
              >
                <Square size={14} fill="currentColor" />
              </button>
            ) : (
              <button
                type="button"
                className="audio-btn"
                onClick={onPlay}
                title="Play Narration"
              >
                <Play size={14} fill="currentColor" />
              </button>
            )}
          </div>
        </div>

        <p className="voice-text">
          &ldquo;{VOICE_NARRATION}&rdquo;
        </p>
      </div>
    </div>
  )
}
